model_name: xdxd_spacenet4

model_path: '//home/wb447340/Notebooks/Imagery/Feature_Extraction/GHA_RGB_Model.pth'
train: true
infer: false

pretrained: true
nn_framework:  torch
batch_size: 48

data_specs:
  width: 256
  height:  256
  image_type: zscore
  rescale: true
  rescale_minima: auto
  rescale_maxima: auto
  channels: 3
  label_type: mask
  is_categorical: true
  mask_channels: 1
  val_holdout_frac: 0.1
  data_workers:

training_data_csv: '//home/wb447340/Notebooks/Imagery/Feature_Extraction/GHA_train_lnx_2.csv'
validation_data_csv:
inference_data_csv: '//home/public/Data/COUNTRY/GHA/chippedbasemap_512/all_images_INF.csv'

training_augmentation:
  augmentations:
    SwapChannels:
      axis: 2
      first_idx: 0
      second_idx: 2
      p: 1.0
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 256
      width: 256
      p: 1.0
    Normalize:
      mean:
        - 67.877164
        - 86.458291
        - 52.611754
      std:
        - 19.532013
        - 11.783424
        - 11.041608
      max_pixel_value: 255
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    SwapChannels:
      axis: 2
      first_idx: 0
      second_idx: 2
      p: 1.0
    CenterCrop:
      height: 256
      width: 256
      p: 1.0
    Normalize:
      mean:
        - 67.877164
        - 86.458291
        - 52.611754
      std:
        - 19.532013
        - 11.783424
        - 11.041608
      max_pixel_value: 255
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    SwapChannels:
      axis: 2
      first_idx: 0
      second_idx: 2
      p: 1.0
    Normalize:
      mean:
        - 67.877164
        - 86.458291
        - 52.611754
      std:
        - 19.532013
        - 11.783424
        - 11.041608
      max_pixel_value: 255
      p: 1.0
  p: 1.0
training:
  epochs:  6
  steps_per_epoch:
  optimizer: Adam
  lr: 1e-9
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 12
    jaccard: 0.9
  metrics:
    training:
    validation:
  checkpoint_frequency: 10
  callbacks:
    model_checkpoint:
      filepath: '//home/wb447340/Notebooks/Imagery/Feature_Extraction/models/GHA2_model_checkpoint.pth'
      monitor: val_loss
  model_dest_path: '//home/wb447340/Notebooks/Imagery/Feature_Extraction/models/GHA2_RGB_Model.pth'
  verbose: true

inference:
  window_step_size_x:
  window_step_size_y:
  output_dir: '//home/wb447340/Notebooks/Imagery/Feature_Extraction/PREDICTIONS_RGB'
